{% set version = "0.8.13" %}

package:
  name: ncagg 
  version: {{ version }}

source:
  url: https://github.com/5tefan/ncagg/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d5ebef41b241b79483499d5664120df8aa4213127104803640d46b575452db08

build:
  noarch: python
  entry_points:
    - "ncagg = ncagg.cli:cli"
  number: 0
  script: 
    - "{{ PYTHON }} -m pip install . -vv"
    - python -m unittest discover -s $SRC_DIR

requirements:
  host:
    - python >=3.7
    - pip
    - numpy
    - netcdf4
    - cerberus >=1.3,<1.4
    - click >=7.1,<7.2
  run:
    - python >=3.7
    - numpy
    - netcdf4
    - cerberus >=1.3,<1.4
    - click >=7.1,<7.2

test:
  imports:
    - ncagg
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/5tefan/ncagg
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Combine multiple netCDF files into one.'
  description: |
    ncagg is a flexible aggregation software that combines multiple netcdf
    files into a single file, with special handling for metadata.
  doc_url: https://ncagg.readthedocs.io/en/latest/ 
  dev_url: https://github.com/5tefan/ncagg

extra:
  recipe-maintainers:
    - khallock
    - 5tefan
